### PR TITLE
add `insert` to DispatcherBuilder to not consume it

### PR DESCRIPTION
**Pull request by tgolsson**
This makes it possible to store the dispatcher builder in another builder, and to pass it around a bit more easily to plugins.

I also snuck in a small `iter_stages()` function for debugging, I can pop that out and make a separate PR if you prefer.

### CODE REVIEW

**Comment by AnneKitsune** [comment]
Do you think it would be preferable to use only the insert methods going forward? If the add* method aren't being used and instead only the insert* methods would be used, we could replace the current functions with yours?

**Comment by tgolsson** [comment]
I think that `add` is nice; there's some very unergonomic sides to `&mut Self` as the return type of a builder. And for smaller projects it's just easier to `.add(...).add(...)` when you don't run multiple dispatchers or use too many systems.

**Comment by AnneKitsune** [comment]
I thought about this for a while. Can we rename `.insert` to `.with` and also add a test that uses chaining? :
```rust
DispatcherBuilder::new().with_system(...).with(...).build(&mut world)
```

Thanks :)

**Comment by tgolsson** [comment]
@jojolepro I guess it'd be `add` that goes to `with`? You can't chain `insert` into `build` since it returns `&mut Self`, which can't be sunk. As in; the two options:

```rust
let dispatcher = DispatcherBuilder::new()
    .with(...)
    .with(...)
    .build(&mut world);
```

```rust
let mut builder = DispatcherBuilder::new();

builder
    .insert(...)
    .insert(...);

let runtime = builder.build(&mut world);
```

**Comment by AnneKitsune** [comment]
I think I'm missing the point. What is the purpose of .insert that isn't covered by .add ?

**Comment by tgolsson** [comment]
Currently, it is impossible to do something like:

```rust
mod audio {
   fn submit_clips(...) -> SystemResult { /* snip */ }

   pub fn add_functions(builder: &mut DispatcherBuilder) {
       builder.add(submit_clips);
   }
}
```

So that's why I need a function that doesn't consume self. 

In theory, this case *could* work as:

```rust
mod audio {
   fn submit_clips(...) -> SystemResult { /* snip */ }

   pub fn add_functions(mut builder: DispatcherBuilder) -> DispatcherBuilder {
       builder.add(submit_clips);
   }
}
```

but I use multiple builders; like so:

```rust
struct RuntimeBuilder {
    begin_frame_builder: DispatcherBuilder,
    update: DispatcherBuilder,
    /* etc */
    component_types: Vec<Box<dyn ComponentDescriptor>>,
}
```

and then you need pass that whole thing around, all members need to be public to be able to destruct/construct etc.

**Comment by AnneKitsune** [comment]
I see. Would this do the trick for your use case? https://crates.io/crates/planck_ecs_bundle

**Comment by tgolsson** [comment]
Hmm. I could implement the trait for another builder structure and then inject them all in one go. But that's pretty much just replacing the dispatcher builder. (And since Bundle can't be a Value, it doesn't quite work either way.)

Ie, this works:

```rust

pub struct PassBuilder {
    systems: Vec<System>,
}

impl PassBuilder {
    pub fn insert<U, T: IntoSystem<U>>(&mut self, system: T) -> &mut Self {
        self.systems.push(system.system());
        self
    }

    pub fn add<U, T: IntoSystem<U>>(mut self, system: T) -> Self {
        self.systems.push(system.system());
        self
    }
}

trait AlmostBundle {
    // N.b., takes `self`
    fn insert(self, builder: DispatcherBuilder) -> DispatcherBuilder;
}

impl AlmostBundle for PassBuilder {
    fn insert(self, mut builder: DispatcherBuilder) -> DispatcherBuilder {
        for system in self.systems {
            builder = builder.add_system(system);
        }
        builder
    }
}

```

But in that case, I could as easily do:

```rust
impl  PassBuilder {
    fn build(self, world: &mut World) -> Dispatcher {
        let mut builder = DispatcherBuilder::new();
        for system in self.systems {
            builder = builder.add_system(system);
        }
        builder.build(world)
    }
}
```

Which maybe is what I should do, if you feel this is out of scope for world_dispatcher.

**Comment by AnneKitsune** [comment]
I think this would fit really nicely into a planck_ecs_pass_builder or something. Would it change anything to your analysis if we make systems: Vec<System> public inside of DispatcherBuilder?

For example, you could create a "plug in" trait which adds the method you want:
```rust
trait DispatcherBuilderHelper<T> {
    fn insert(self, system) -> T;
}
impl DispatcherBuilderHelper<DispatcherBuilder> for DispatcherBuilder {
    fn insert(self, system) -> DispatcherBuilder {
        self.systems.push(system);
        self
    }
}
```
I'm not against adding insert to the crate, just trying to figure out where it would best to place the code. This crate has a strong philosophy of trying to avoid having multiple ways of doing the same thing, so if we can make insert as a new plug in crate that will avoid cluttering. Let me know what you think!

**Comment by tgolsson** [comment]
Making it public sounds like a great idea, then I can either keep it on my end or make an extension crate/repo (or make planck_ecs a workspace in a single repo?)

**Comment by AnneKitsune** [comment]
Best option would seem to have an extension crate, the same way plank_ecs_bundle adds to the base crate :)

**Comment by tgolsson** [comment]
Closing in favor of the other PR.

**Pull request closed without merging**
